### ISSUE TITLE
macosx: Fix wheel creation

### ISSUE THREAD

**Issue by jcfr** [jcfr/cmake-python-distributions#2]
Source: https://travis-ci.org/jcfr/cmake-python-distributions/jobs/166645184

```
loading initial cache file /Users/travis/build/jcfr/cmake-python-distributions/_skbuild/cmake-build/CMakePythonDistributions-prefix/tmp/CMakePythonDistributions-cache-Release.cmake

CMake Error at CMakeLists.txt:339 (install):
  install FILES given directory
  "/Users/travis/build/jcfr/cmake-python-distributions/_skbuild/cmake-build/CMakeProject-binary-distribution/CMake.app/Contents/Frameworks/QtCore.framework/Resources"
  to install.

CMake Error at CMakeLists.txt:339 (install):
  install FILES given directory
  "/Users/travis/build/jcfr/cmake-python-distributions/_skbuild/cmake-build/CMakeProject-binary-distribution/CMake.app/Contents/Frameworks/QtCore.framework/Versions/Current"
  to install.

[...]

make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/3.4.5/lib/python3.4/site-packages/skbuild/setuptools_wrap.py", line 337, in setup
    cmkr.make(make_args)
  File "/Users/travis/.pyenv/versions/3.4.5/lib/python3.4/site-packages/skbuild/cmaker.py", line 395, in make
    os.path.abspath(CMAKE_BUILD_DIR)))


An error occurred while building with CMake.
  Command:
    "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
  Source directory:
    /Users/travis/build/jcfr/cmake-python-distributions
  Working directory:
    /Users/travis/build/jcfr/cmake-python-distributions/_skbuild/cmake-build
Please see CMake's output for more information.
Traceback (most recent call last):
  File "/usr/local/bin/ci", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/ci/__main__.py", line 32, in main
    ci.execute_step(args.step)
  File "/usr/local/lib/python2.7/site-packages/ci/driver.py", line 279, in execute_step
    d.execute_commands(step)
  File "/usr/local/lib/python2.7/site-packages/ci/driver.py", line 266, in execute_commands
    self.check_call(cmd.replace("\\\\", "\\\\\\\\"), env=self.env)
  File "/usr/local/lib/python2.7/site-packages/ci/driver.py", line 78, in check_call
    return subprocess.check_call(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '../ci/travis/run-with-pyenv.sh python setup.py build' returned non-zero exit status 1
```

**Comment by jcfr** [comment]
Fixed by 3649302108636f791dcbec2931528545c11cf9e6 and 48335168d436e91ffe6cabc96139cc5cbf298ea7
